

USE master;
GO

SELECT name FROM sys.databases WHERE name = 'BD';
GO

ALTER DATABASE [BD] SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
GO

RESTORE DATABASE [BD] 
FROM DISK = N'C:\SQL_Backup\BD_FullBackup_20260514_115814.bak'
WITH REPLACE, RECOVERY;
GO

ALTER DATABASE [BD] SET MULTI_USER;
GO

USE [BD];
SELECT * FROM [dbo].[Users];
GO